name: "Deploying a Static Web Application"

on:
  push:
    branches:
    - feature
    paths:
    - "app/**"

jobs:
  staging:

    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://lively-water-0d069450f-feature.eastus2.3.azurestaticapps.net
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Use the appropriate Python version
    
      - name: Install dependencies
        run: |
          pip install toml

      - name: Update URL in TOML
        run: |
          TOML_FILE="app/hugo.toml"
          NEW_URL="https://lively-water-0d069450f-feature.eastus2.3.azurestaticapps.net"
          
          # Use Python script to update the URL in the TOML file
          python3 - <<EOF
          import toml

          with open("$TOML_FILE", "r") as f:
              data = toml.load(f)
              data["baseURL"] = "$NEW_URL"

          with open("$TOML_FILE", "w") as f:
              toml.dump(data, f)
          EOF

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "app"
          output_location: "public"
          production_branch: "main"