name: "Deploying a Static Web Application"

on:
  push:
    branches:
    - feature
    paths:
    - "app/**"

jobs:
  staging:

    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://lively-water-0d069450f-feature.eastus2.3.azurestaticapps.net
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Update baseURL in TOML
        run: |
          # Replace 'path/to/your/file.toml' with the actual path to your TOML file
          ls
          TOML_FILE="app/hugo.toml"
          NEW_BASEURL="https://lively-water-0d069450f-feature.eastus2.3.azurestaticapps.net"
          
          # Use sed to update the baseURL in the TOML file
          sed -i "s/baseURL = \".*\"/baseURL = \"$NEW_BASEURL\"/" "$TOML_FILE"

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "app"
          output_location: "public"
          production_branch: "main"