name: "Deploying a Static Web Application"

on:
  push:
    branches:
    - feature
    paths:
    - "app/**"

jobs:
  staging:

    name: Deploy to Staging
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://lively-water-0d069450f-feature.eastus2.3.azurestaticapps.net
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "app"
          output_location: "public"
          production_branch: "main"