name: "Deploying a Static Web Application"

on:
  push:
    branches:
    - main
    paths:
    - "src/**"

jobs:
  bash-example:
    name: Deploying a Static Web Application
    runs-on: ubuntu-latest
    steps:

      - name: "Test"
        run: |
          echo: "Deploying a Static Web Application"