name: "Deploying a Static Web Application"

on:
  push:
    branches:
    - main
    paths:
    - "src/**"

jobs:
  deploy:
    name: Publish Website
    needs: terraform
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "upload"
          app_location: "src"
          output_location: "public"