name: "Build Azure Infrastructure"

on:
  push:
    branches:
    - main
    paths:
    - "terraform/**"
  pull_request:
    - main
    paths:
    - "terraform/**"

jobs:
  terraform:
    name: Build Azure Infrastructure
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout Repositories
        run: actions/checkout@v3

      - name: Set up Terraform
        run:  hashicorp/setup-terraform@v2
        with:
          cli_config_credential_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
      
      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -input=false -no-color

      - name: Update Pull Request 
        uses: actions/github-scripts@v6
        if: github.event_name == 'pull_request'
        env: 
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: | 
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
          
      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
