name: "Build Azure Infrastructure"

on:
  push:
    branches:
    - main
    paths:
    - "terraform"

jobs:
  bash-example:
    name: Build Azure Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "This is a bloody infrastructure"
